---
# main.yml
- name: macOS Tahoe Full Setup
  hosts: localhost
  connection: local
  gather_facts: true

  # Link to your separate configuration file
  vars_files:
    - vars.yml

  tasks:
    - name: Run SSH Setup and enable GitHub Access
      ansible.builtin.include_tasks: tasks/ssh_conf_enable_github.yml
      when: setup_ssh_github

    - name: Run Homebrew Installation
      ansible.builtin.include_tasks: tasks/homebrew.yml
      when: setup_homebrew

    - name: Run Dotfile Symlinking
      ansible.builtin.include_tasks: tasks/symlinks_dotfiles.yml
      when: setup_dotfiles

    - name: Run Application Configuration
      ansible.builtin.include_tasks: tasks/app_conf.yml
      when: setup_app_conf

    - name: Run Dock Configuration
      ansible.builtin.include_tasks: tasks/dock.yml
      when: setup_dock

    - name: Run Folder Creation
      ansible.builtin.include_tasks: tasks/create_folders.yml
      when: setup_create_folders

    - name: Run Symlink Creation
      ansible.builtin.include_tasks: tasks/create_links.yml
      when: setup_create_links
# ---------------------------------------------------------------------------- #

    # - name: Run VS Code Configuration
    #   ansible.builtin.include_tasks: tasks/vscode.yml
    #   when: setup_vscode

    # - name: Run iTerm2 Configuration
    #   ansible.builtin.include_tasks: tasks/iterm2.yml
    #   when: setup_iterm2

    # - name: Run espanso Configuration
    #   ansible.builtin.include_tasks: tasks/espanso.yml
    #   when: setup_espanso

    # - name: Run SSH Client Configuration
    #   ansible.builtin.include_tasks: tasks/ssh_client_config.yml
    #   when: setup_ssh_conf