- name: Create directories
  ansible.builtin.file:
    path: "{{ item.path | default(item) }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
  loop: "{{ directories_to_create }}"
