# tasks/iterm2.yml

- name: Quit iTerm2 to allow preference syncing
  ansible.builtin.shell: osascript -e 'quit app "iTerm"'
  failed_when: false # Don't fail if iTerm wasn't running
  changed_when: false

- name: Ensure iTerm2 configuration directory exists
  ansible.builtin.file:
    path: "{{ iterm_config_dir }}"
    state: directory
    mode: '0755'

- name: Symlink files to config path
  ansible.builtin.file:
    src: "{{ iterm_repo_src }}/{{ item }}"
    dest: "{{ iterm_config_dir }}/{{ item }}"
    state: link
    force: true
  loop: "{{ iterm_files_to_link }}"

- name: Enable loading preferences from custom folder
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: LoadPrefsFromCustomFolder
    type: bool
    value: true

- name: Set path for custom preferences folder
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: "{{ iterm_config_dir }}"
