- name: Ensure SSH directory exists with correct permissions.
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.ssh"
    state: directory
    mode: '0700'

- name: Configure SSH conf file for GitHub andto use macOS Keychain
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['user_dir'] }}/.ssh/config"
    create: true
    mode: '0600'
    block: |
      Host github.com
        AddKeysToAgent yes
        UseKeychain yes
        IdentityFile {{ ssh_key_path }}

- name: Check if SSH key exists in the .ssh folder.
  ansible.builtin.stat:
    path: "{{ ssh_key_path }}"
  register: ssh_key_stat

- name: Fail if SSH key is missing
  ansible.builtin.fail:
    msg: "SSH key not found at {{ ssh_key_path }}. Please generate it and add to GitHub first!"
  when: not ssh_key_stat.stat.exists
