# VS Code - Extensions
- name: Install VS Code extensions
  block:
    - name: Install Visual Studio Code extensions
      ansible.builtin.shell:
        cmd: "'/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code' --install-extension {{ item }}"
      loop: "{{ vscode_extensions }}"
      register: vscode_result
      changed_when: "'successfully installed' in vscode_result.stdout"
      failed_when: 
        - vscode_result.rc != 0 
        - "'already installed' not in vscode_result.stdout"
  # This block only runs if your variable is true
  when: setup_vscode_extensions | default(false) | bool

# VS Code - User Settings
- name: Configure VS Code User Settings
  block:
  - name: Ensure VS Code User configuration directory exists
    ansible.builtin.file:
      path: "{{ vscode_config_dir }}"
      state: directory
      mode: '0755'
  
  - name: Symlink VS Code settings.json
    ansible.builtin.file:
      # UPDATED: We now use the variable directly since it contains the full path
      src: "{{ vscode_settings_file }}"
      dest: "{{ vscode_config_dir }}/settings.json"
      state: link
      force: true
      mode: '0644'
  # This block only runs if your variable is true
  when: setup_vscode_user_settings | default(false) | bool  

# VS Code - File Handling
- name: Configure VS Code as default for Markdown
  block:
    - name: Ensure duti is installed
      community.general.homebrew:
        name: duti
        state: present

    - name: Set VS Code as default for other text files
      ansible.builtin.command:
        cmd: "duti -s com.microsoft.VSCode {{ item }} all"
      loop: "{{ vscode_file_handling }}"
      changed_when: false
      
  # This block only runs if your variable is true
  when: setup_vscode_file_handling | default(false) | bool